"""Initial model restaurant inspection

Revision ID: 5785ee6a8724
Revises: 
Create Date: 2017-12-25 23:40:40.376658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5785ee6a8724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('camis', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dba', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('building', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('boro', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cuisine_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('camis', name=u'restaurant_pkey')
    )
    op.create_table('inspection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('camis', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inspection_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('violation_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('violation_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('critical_flag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grade_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'inspection_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
